### ISSUE TITLE
TraderKeeper single-user

### ISSUE THREAD

**Issue by jorisbontje** [MakerDAO/maker-market-matcher#2]
To simplicate the flow, first focus on having the TraderKeeper work with a simple user (= owner)

* In the constructor store who the owner is of the proxy contract
* expose getBalance to see how many tokens are stored in the contract
* withdraw only accessible by the owner
* expose getting / setting the allowance

**Comment by jorisbontje** [comment]
Done?

**Comment by freekp** [comment]
Yes, done!
