### ISSUE TITLE
check token transfer success

### ISSUE THREAD

**Issue by nmushegian** [MakerDAO/maker-market-matcher#3]
revert if `transfer` return false

**Comment by jorisbontje** [comment]
What line / function do you refer to? Inside the `trade` function the `assert` will already do a revert... so maybe you mean somewhere else?

**Comment by rainbeam** [comment]
I think both the `transfer` and `transferFrom` calls:

https://github.com/MakerDAO/maker-market-matcher/blob/master/contracts/TraderKeeper.sol#L19

https://github.com/MakerDAO/maker-market-matcher/blob/master/contracts/TraderKeeper.sol#L24

These return `bool ok` to indicate success or not and EIP20 doesn't guarantee a `throw` for unsuccessful calls.

**Comment by jorisbontje** [comment]
Ah I see, these functions were not intended to be called via other contracts, but then again why shouldn't they. We'll add some assertions.
